language: objective-c
osx_image: xcode8
before_install:
  - brew remove --force $(brew list)
  - brew cleanup -s
  - rm -rf $(brew --cache)
  - brew update
install:
  - mkdir -p $(brew --repo)/Library/Taps/travis
  - ln -s $PWD $(brew --repo)/Library/Taps/travis/homebrew-testtap
  - brew tap --repair
  - gem install rubocop --no-document
env:
  - PACKAGE=speculid
script:
  - rubocop --config=$(brew --repo)/Library/.rubocop.yml Formula/$PACKAGE.rb
  - brew audit $PACKAGE
  - brew install -v $PACKAGE
  - brew test $PACKAGE