language: objective-c
osx_image: xcode10.1
before_install:
  - brew remove --ignore-dependencies --force $(brew list)
  - brew cleanup -s
  - rm -rf $(brew --cache)
  - brew update
  - brew install openssl libyaml
install:
  - mkdir -p $(brew --repo)/Library/Taps/travis
  - ln -s $PWD $(brew --repo)/Library/Taps/travis/homebrew-testtap
  - brew tap --repair
env:
  - PACKAGE=speculid
script:
  - brew cask audit Formula/speculid.rb --download
  - brew cask install Formula/speculid.rb 
  - brew cask style Formula/speculid.rb
