language: objective-c
osx_image: xcode8
before_install:
  - brew update
install:
  - mkdir -p $(brew --repo)/Library/Taps/travis
  - ln -s $PWD $(brew --repo)/Library/Taps/travis/homebrew-testtap
  - brew tap --repair
env:
  - PACKAGE=speculid
script:
  - brew audit --strict --online $PACKAGE
  - brew install -v $PACKAGE
  - brew test $PACKAGE